name: Build and publish documentation

on:
    push:
      branches:
        - main
    pull_request:
  
jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false

